export const APP_PROMPT_SUGGESTIONS: Record<string, string[]> = {
  VITE_APP: [
    "Build a stunning personal portfolio with glassmorphism and smooth animations",
    "Create a SaaS dashboard with interactive charts and a user management table",
    "Build a real-time weather application with 7-day forecasts and location search",
    "Create a clean, minimalist todo list with drag-and-drop task reordering",
    "Build a digital recipe book with categorization and ingredient search",
    "Create an expense tracker with category-based breakdown and data visualization",
    "Build a modern quiz application with timed questions and a leaderboard",
    "Create a markdown editor with real-time preview and export functionality",
    "Build a Pomodoro timer with customizable sessions and ambient sounds",
    "Create an e-commerce product grid with fast filtering and a persistent cart",
    "Build a job search board with advanced filtering and application tracking",
    "Create a movie database browser with reviews and trailer integrations",
    "Build a fitness tracker dashboard with workout logging and progress charts",
    "Create a social media feed mockup with image uploads and like interactions",
    "Build a survey builder with multiple question types and response analytics",
    "Create a music player UI with playlists, playback controls, and visualizers",
    "Build a note-taking application with rich text editing and cloud sync",
    "Create a collaborative drawing canvas with multiple tools and export options",
    "Build a loan calculator with amortization schedules and visual representations",
    "Create a habit tracker with streak counting and weekly progress visualizations",
    "Build an event management platform with scheduling and attendee tracking",
    "Create a cryptocurrency price tracker with real-time updates and historical data",
    "Build a clean marketing agency landing page with service sections and forms",
    "Create an interactive map application for exploring local tourism spots",
    "Build a team collaboration dashboard with task boards and a team calendar"
  ],
  NEXT_APP: [
    "Build a high-conversion SaaS landing page with dark mode and pricing plans",
    "Create a full-stack blog platform with markdown support and an admin dashboard",
    "Build a real estate listing site with advanced search filters and map integration",
    "Create a community forum with nesting comments and user reputation system",
    "Build a project management tool with Kanban boards and team collaboration",
    "Create a multi-vendor e-commerce platform with search and secure checkout",
    "Build an analytics dashboard with real-time data fetching and custom reports",
    "Create a documentation site with MDX support, search, and version control",
    "Build a booking system for restaurants with seat selection and notifications",
    "Create a recruitment portal with job postings and applicant management",
    "Build a subscription-based newsletter platform with email integrations",
    "Create a dynamic portfolio with ISR for fast loading and easy content updates",
    "Build an inventory management system with stock tracking and alerts",
    "Create a multi-step form builder with validation and conditional logic",
    "Build a learning management system with courses, lessons, and progress tracking",
    "Create a social network MVP with user profiles, feeds, and real-time chat",
    "Build a real-time notification system with custom triggers and user settings",
    "Create a global marketplace with multi-currency support and localized content",
    "Build an automated SEO auditing tool with readability and performance analysis",
    "Create a resource library with tagging, search, and user-generated content",
    "Build a cloud file management system with folder organization and sharing",
    "Create a team messaging application with channels and direct messaging",
    "Build a dynamic event ticketing system with QR code generation and validation",
    "Create a customer support portal with ticketing and knowledge base search",
    "Build a portfolio showcasing 3D elements with Three.js and Next.js integration"
  ],
  EXPRESS_APP: [
    "Build a robust REST API for an e-commerce platform with RBAC and JWT",
    "Create a real-time chat server using Socket.io with channel support",
    "Build a file storage service with cloud provider integration and metadata",
    "Create an authentication microservice with OAuth2 and multi-factor support",
    "Build a data scraping API that provides structured JSON from multiple sites",
    "Create a payment gateway integration service supporting multiple providers",
    "Build an automated notification service for Email, SMS, and Push updates",
    "Create a high-performance URL shortener with analytics and custom aliases",
    "Build a task scheduling engine for background jobs and recurring workflows",
    "Create a centralized logging system with structured logs and search",
    "Build a resource tracking API for inventory management in microservices",
    "Create a GraphQL gateway that aggregates data from multiple REST endpoints",
    "Build a health monitoring service for checking the status of distributed APIs",
    "Create a user feedback and survey API with sentiment analysis capabilities",
    "Build a rate-limiting and security middleware for high-traffic applications",
    "Create a caching layer using Redis for frequently accessed database queries",
    "Build a blog CMS backend with rich text management and asset handling",
    "Create a social media backend with complex relationships and feed generation",
    "Build a workout logging API with exercises, sets, and progress tracking",
    "Create a recipe database API with ingredient search and nutritional data",
    "Build a community forum API with voting, moderation, and flagging tools",
    "Create an IoT device management API for tracking and controlling sensors",
    "Build a localization and translation service for managing multi-language content",
    "Create a simple database migration utility for various relational databases",
    "Build an API for a personal finance manager with recurring expense detection"
  ],
  EXPO_APP: [
    "Build a feature-rich food delivery mobile app with menus and tracking",
    "Create a fitness tracking app with workout logging and progress metrics",
    "Build a meditation app with audio playback and mindfulness exercises",
    "Create a travel guide mobile application with maps and points of interest",
    "Build a personal finance manager with expense tracking and budget alerts",
    "Create a habit builder mobile app with streaks and visual reminders",
    "Build a smart home controller UI for managing lighting and temperature",
    "Create a crypto wallet mobile interface with price charts and asset history",
    "Build a real estate discovery app with filters and favorite listings",
    "Create a matching-based social app UI with swiping and direct messages",
    "Build a mobile job search board with application status tracking",
    "Create an event discovery app for local workshops and community events",
    "Build a music streaming mobile UI with playlists and playback controls",
    "Create a health and wellness app with water tracking and sleep logs",
    "Build a news reader mobile app with categorized feeds and bookmarks",
    "Create an e-commerce shopping app with product search and secure cart",
    "Build a recipe discovery mobile app with step-by-step cooking guides",
    "Create a mobile portfolio showcasing creative works and case studies",
    "Build a learning app with interactive lessons and progress badges",
    "Create an inventory scanner mobile app with barcode/QR code support",
    "Build a mobile messaging application with real-time chat and media sharing",
    "Create a car rental booking app with car filters and reservation history",
    "Build a task management mobile app with collaborative shared lists",
    "Create a local tourism exploratory app with personalized recommendations",
    "Build a mobile dashboard for viewing metrics from connected IoT devices"
  ]
};
