export const DB_NAME = "open-library";

export const SendMailEnum = {
  VERIFY_EMAIL: "VERIFY_EMAIL",
  RESET_PASSWORD: "RESET_PASSWORD",
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
  VERIFY_EMAIL_FAILURE: "VERIFY_EMAIL_FAILURE",
  WELCOME: "WELCOME",
  ACCOUNT_ACTIVATION: "ACCOUNT_ACTIVATION",
  ACCOUNT_DEACTIVATION: "ACCOUNT_DEACTIVATION",
  ACCOUNT_SUSPENSION: "ACCOUNT_SUSPENSION",
  ACCOUNT_REACTIVATION: "ACCOUNT_REACTIVATION",
  PASSWORD_CHANGE_NOTIFICATION: "PASSWORD_CHANGE_NOTIFICATION",
  TWO_FACTOR_AUTHENTICATION: "TWO_FACTOR_AUTHENTICATION",
  NEWSLETTER_SUBSCRIPTION: "NEWSLETTER_SUBSCRIPTION",
  PROMOTIONAL_OFFER: "PROMOTIONAL_OFFER",
  TOO_MANY_FAILED_LOGIN_ATTEMPTS: "TOO_MANY_FAILED_LOGIN_ATTEMPTS",
};

export const UserRoleEnum = {
  ADMIN: "ADMIN",
  USER: "USER",
  MODERATOR: "MODERATOR",
  GUEST: "GUEST",
};

export const UserStatusEnum = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED",
};


export const BookGenreEnum = {
  FICTION: "Fiction",
  NON_FICTION: "Non-Fiction",
  SCIENCE_FICTION: "Science Fiction",
  FANTASY: "Fantasy",
  BIOGRAPHY: "Biography",
  HISTORY: "History",
  MYSTERY: "Mystery",
  ROMANCE: "Romance",
  HORROR: "Horror",
  PROGRAMMING: "Programming",
  OTHER: "Other",
};